---
title: "Detailed model formulation, analysis, and results"
subtitle: "**Supplemental Information for:** Developing a protocol for estimation of red deer (*Cervus elaphus*) population density using drones in a steep and rugged terrain"
# Sjekk hva endelig tittel blir
date: now
authors: <to be inserted after peer-review>
project:
  type: default
  execute-dir: project
number-sections: true
toc: true
toc-depth: 4
format:
  html:
    embed-resources: true
    theme: journal
bibliography: references.bib
---

```{r}
#| echo: false
#| output: false
Sys.setlocale(locale='no_NB.utf8') # Include for using Norwegian letters in plots
library(knitr)
library(coda)
source("../R/utilities.r")
```

This document presents details about the model results, including convergence diagnostics, posterior predictive checks, tables and figures. The document is written in Quarto, and the source file containing all executable R code is available in the GitHub-repository accompanying the paper (zip-file provided for per review).

# Detailed model formulation

Deer densities were estimated using hierarchical state space models fitted by the use of Bayesian Markov Chain Monte Carlo (MCMC) sampling in NIMBLE ver. 1.1.0 [@valpine_programming_2017; @devalpine2024]. We combined a double-observer observation model with an overdispersed Poisson process model describing the variation in deer densities among sampling sites (focal images). We will here first derive the observation model and the process model, using a hierarchical formulation, and then provide details about the analysis. The NIMBLE model code, together with the data, are provided on GitHub (\<URL will be inserted after peer-review; a zip-file is provided for peer-review\>).

To estimate abundance and population density, one must account for the fact that not all individuals that are present will be observed (i.e., imperfect detection). We used a double observer protocol to estimate detection probabilities [@nichols2000; @williams2002]. At each site (focal image) $i$ we have records of how many individuals that were seen by only observer 1 ($y_{10,i}$), how many individuals were seen by only observer 2 ($y_{01,i}$), and how many individuals were seen by both observers ($y_{11,i}$). We denote the observed data from each site by a vector $\mathbf{y}_i = \left[y_{01,i},y_{10,i},y_{11,i} \right]$, and the number of individuals seen by at least one observer is the sum of the elements in this vector, $\mathbf{Y}_i = y_{01,i} + y_{10,i} + y_{11,i}$. The observation model defined in the first section below describes the probability (likelihood) of getting these observed data, conditional on the number of individuals ($N_i$) present at each site; i.e. $L(\mathbf{y}_i |N_i)$. The number of individuals at each site, $N_i$, is unknown, and the stochastic model for this is described in the next section.

## Observation model

Given that the two observers detect individuals independently with probabilities $p_1$ and $p_2$ respectively, the probability that an individual is detected by only observer 1 is $P_{10} = p_1 (1-p_2)$, the probability of only being detected by observer 2 is $P_{01} = (1-p_1)p_2$, and the probability of being detected by both observers is $P_{11} = p_1 p_2$. The probability of being detected by at least one observer is one minus the probability of not being detected by any of the observers, $p^* = 1-(1-p_1)(1-p_2)$. Note that this is equivalent to $p^* = P_{10} + P_{01} + P_{11}$.

The key to derive a model for the observed data ($L(\mathbf{y}_i│N_i)$), is to first write the probability of the observed data conditional on the number of individuals seen by at least one observer ($Y_i$), and then multiply this with the probability of observing $Y_i$. I.e., $L(\mathbf{y}_i│N_i) = L(\mathbf{y}_i|Y_i)L(Y_i|N_i)$. The first of these components is a multinomial likelihood, and the second component is a binomial likelihood. Hierarchically, we write this as

$$
\begin{align}
\mathbf{y}_i  &\sim \text{Multinomial} (\pi,Y_i) \\
Y_i  &\sim \text{Binomial}(p^*,N_i)   
\end{align}
$$

where $\pi=[P_{10},P_{01},P_{11} ]/p^*$ (i.e., the multinomial probability vector $\pi$ contains the probabilities of the three detection categories conditional on detection). Note that all observed individuals must belong to one, and only one, of the three detection categories, and hence the elements of $\pi$ sum to one. Note also that when $Y_i=0$, the multinomial probability of observing $\mathbf{y}_i=[0,0,0]$ becomes 1 regardless of the parameter values.

This initial observation model has only two top level parameters: the detection probabilities of the two observers, $p_1$ and $p_2$ (these could have been made site specific, and then been modelled as a function of covariates on e.g. a logit scale). Posterior predictive checks (see below) indicated, however that the two independent observers had sufficiently variable detection probabilities among sites to call for a model with random detection probabilities – see details below.

## Process model

The number of individuals present at a site was modelled as an overdispersed Poisson process. Hence, we assume that number of individuals present at site $i$, $N_i$, is drawn from a Poisson distribution with expectation $\lambda_i a_i$, where $\lambda_i$ is the expectation per unit area (we used hectares) and $a_i$ is the area of the site, $$
N_i  \sim \text{Poisson}(\lambda_i a_i)
$$

Overdispersion was accommodated by modelling $\lambda_i$ as a random variable. As we anticipated that density estimates may be somewhat sensitive to the choice of the distribution of $\lambda_i$, we examined three alternative random distributions; log-normal, exponential, and gamma.

### Log-normal expectation

For the log-normal model we used a standard log-linear log-normal model, $$
\begin{align}
\log(\lambda_i) &\sim N(\mu_i, \sigma^2) \\
\mu_i &= x_i \beta
\end{align}
$$

where $x_i$ is a vector of site-covariates and $\beta$ is a vector of the linear coefficients (including an intercept). Mean deer density in the log-normal model is then $e^{\mu_i+\sigma^2/2}$ and the variance is $(e^{\sigma^2}-1) e^{2\mu_i+\sigma^2}$.

### Exponential expectation

The exponential distribution is a one-parameter distribution with probability density function $f(\lambda) = \Lambda e^{-\Lambda\lambda}$, expectation $1/\Lambda$, and variance $1/\Lambda^2$. We modeled the expectation as a log-linear function of covariates (i.e., assuming multiplicative effects), and hence formulated the model hierarchically as

$$
\begin{align}
\lambda_i  &\sim \text{Exponential}(\Lambda_i) \\
\Lambda_i &= e^{-\mu_i} \\
\mu_i &= \mathbf{x}_i \boldsymbol{\beta}
\end{align}
$$

Mean deer density in the exponential model thus becomes $e^{\mu_i}$ and the variance is $e^{2\mu_i}$.

### Gamma expectation

The gamma distribution parameterized with a shape parameter $a$ and a rate parameter $b$ has probability density function $f(\lambda) = \frac{b^a}{\Gamma(a)} \lambda^{a-1} e^{-\beta\lambda}$, expectation $\frac{a}{b}$, and variance $\frac{a}{b^2}$ (the variance is proportional to the mean). We initially tried keeping the rate parameter constant and using a log-linear covariate model for the expectation (i.e., $a_i = be^{\mathbf{x}_i\boldsymbol{\beta}}$), but this model had very poor mixing, even when using blocked mcmc-sampling (perhaps because $b$ is a parent of $a$). Hence, we instead kept the shape parameter constant and let the rate parameter depend on $\mu_i$ and $\sigma$ in such a way that the variance-mean relationship is the same as in the log-normal model (the variance is proportional to the square of the mean),

$$
\begin{align}
\lambda_i  &\sim \text{Gamma}(a,b_i) \\
b_i &= ae^{-(\mu_i+\sigma^2/2)} \\
a &= \frac{1}{e^{\sigma^2} - 1} \\
\mu_i &= \mathbf{x}_i \boldsymbol{\beta}
\end{align}
$$

Hence, mean and variance of deer density in the gamma model has the same expressions as in the log-normal model, respectively $\frac{a}{b} = e^{\mu_i+\sigma^2/2}$ and $a/b^2 = \left( e^{\sigma^2}-1 \right) e^{2\mu_i+\sigma^2 }$. Compared to the log-normal distribution with the same mean and variance, the gamma distribution has lower density far out in the tail of the distribution.

## Modelling of covariate effects

In our application, we included the distance from the agricultural field as the only site covariate in $\mathbf{x}_i$. The covariate effect was the same in all sampling area-month combinations, but the intercept was allowed to vary across area-months. Denoting the index for the area-month that site $i$ belong to as $j(i)$, we can formulate the covariate model as,

$$
\mu_i = \mu_{0,j(i)} + x_i \beta
$$

In principle, $\mathbf{x}_i$ can include both covariates that vary among sites within sampling areas and covariates that vary only among, and not within, sampling areas. However, it is important to realize that if $\mathbf{x}_i$ includes sampling area covariates, random effects of sampling areas would need to be included in order to avoid pseudoreplication (sites within sampling areas is not a random sample of sites with the same sampling area covariate value).

## Estimating densities at the specific sites included in each survey

The estimators for mean density presented above assume that the sites are random samples of a large number of sites of the same characteristics, and the estimates apply to this statistical population of sites. We also computed estimates of density (at the time of flight) at the specific sites included in each survey as the estimated number of individuals present divided by the total area covered, $\bar{d}_s =\sum_{i=1}^n \hat{N}_i/\sum_{i=1}^n a_i$ (the sums are over all $n$ sites in the survey and the subscript $s$ in $\bar{d}_s$ indicates that the mean only applies to the specific sites sampled).

## Estimating number of deer in a specific area

When estimating number of deer in a specific area, such as in the deer enclosures, simply computing the posterior of $N_{\text{Tot}} = \bar{d}_s/q$ were $\bar{d}_s$ is the mean density at the surveyed sites (previous section) and $q$ is the proportion of the area included in survey, will underestimate the sampling variance (uncertainty) of the total number of deer in the area since density in the sampled and unsampled part of the area would not be exactly the same.

To compute the sampling variance of mean number of deer at sample units, we must account for the fact that we sample from a finite area without replacement. It is not straightforward to do this in a Bayesian setting [@banerjee2024], and our case is further complicated by the fact that sample sites vary in size (particularly in the deer enclosures, where parts of the focal images were outside the enclosures). Hence, since we only have a finite sampling area in the deer enclosure, and we only estimate number of deer in the enclosure as a proof of concept, we took a more frequentist approach to the problem, ignoring the fact that sites are of different sizes:

If $n$ sites are sampled from an area covering $K$ sites, the standard expression for the sampling variance of the mean number of deer in the $K$ sites is $$
\text{Var}(\bar{N}) = \frac{K-n}{K} \frac{s^2}{n} 
$$ where $s^2$ is is the empirical variance in number of individuals per site. The first factor is the proportion of the $K$ sites that are *not* included in the sample, and the variance becomes zero when we have counts of the entire area (when $n = K$).

The total number of deer in the area is $N_{\text{Tot}} = K\bar{N}$ with sampling variance $\text{Var} \left( N_{\text{Tot}} \right) = K^2 \text{Var} \left( \bar{N} \right)$. Replacing with the proportion of the area covered in the sample, $q = n/K$ and inserting the expression for $\text{Var}(\bar{N})$, we get

$$
\text{Var} \left( N_{\text{Tot}} \right) = \left( \frac{n}{q} - n \right) \frac{s^2}{q}
$$
(see also @williams2002a chapt. 12.4.1).

In our situation, we do not have exact counts of number of deer per site (due to imperfect detection), but instead we have posterior samples of $N_i$ at each site $i$. To assess the uncertainty in $N_{\text{Tot}}$, we computed posterior samples for lower and upper 95% confidence limits assuming a normal distribution (by the central limit theorem) at the log-scale, using the delta-method approximation,

$$
\text{CI} = \exp(\log(N_{\text{Tot}}) \pm 2 N_{\text{Tot}}^{-1}s)
$$



## Specification of priors and starting values

For the observation model parameters $p_1$ and $p_2$ (detection probabilities) it is natural to use uninformative priors such as $\text{Uniform}(0,1)$. We made, however, use of data from trials at a deer enclosure in a natural habitat to inform the priors for these parameters (detailed below).

The covariate (distance from field) was normalized by subtracting the mean and dividing by the standard deviation prior to model fitting, and we used a $\text{N}(0,\sigma=2)$ prior for the covariate effect, $\beta$.

One approach to the modelling could have been to specify somewhat informative priors for the intercepts $\mu_{0,j(i)}$ based on prior knowledge of reasonable deer densities in the area. However, due to the methodological nature of our study, we decided to use essentially uninformative priors for $\mu_{0,j(i)}$, $\text{N}(0,\sigma=10)$.

To find reasonable starting values for the MCMC-chains, we first computed estimates of $p_1$ and $p_2$ as the proportion of those individuals that were seen by observer 2 that were also seen by observer 1 and vice versa. Simplified estimates of population densities were then computed from the deer counts, the estimated areas of the sites, and the initial estimates of $p_1$ and $p_2$ (see code for details <link to GitHub repository will be inserted after peer review>).

For the log-normal and the gamma models, the prior distribution for $\sigma$ was specified as $\text{Uniform}(0.5,3)$. The lower bound of $0.5$ was set to prevent poor mixing when the mcmc-chains occasionally entered the lower tail of the posterior distribution. The chains never got close to the upper bound of $3$.

In @sec-S2 <MORE DETAILED REF>, we present computed overlap between prior and posterior distributions for all parameters.

## Making use of known density in deer enclosure to inform priors on detectability

The deer density in the enclosure at the deer farm was known, and this may be used to inform the priors for detection probability. The enclosure surrounded a natural habitat with a similar forest type as at the sampling areas. It is therefore reasonable to assume that detection probabilities inside and outside the enclosure are similar. It is, however, not reasonable to assume that the variation in deer densities among sites (focal images) are similar because the enclosure had much higher density, much more females than males, many young individuals, and there were feeding stations where the deer tended to aggregate. Hence, to estimate posterior distributions for detection probabilities, we kept the same model structure as above with a log-normal expected density, but made $\mu$ a function of known mean density ($d$) and the unknown variance in density ($\sigma^2$). As density was modelled as a log-normal distribution, mean density is $d = e^{\mu+\sigma_\varepsilon^2/2}$, and hence we get $\mu = \log(d)-\sigma_\varepsilon^2 / 2$ (we did not model $\mu$ as a function of covariates since the habitat within the enclosure was very homogenous). Hence, we used the following hierarchical model:

$$
\begin{align}
\mathbf{y}_i  &\sim \text{Multinomial}(\pi,Y_i) \\
Y_i  &\sim \text{Binomial}(p^*,N_i )  \\   
N_i &\sim \text{Poisson}(\lambda_i a_i) \\
\log(\lambda_i) &= \mu + \varepsilon_i \\
\mu &= \log⁡(d)-\sigma_\varepsilon^2/ 2\\
\varepsilon_i &\sim N(0,\sigma_\varepsilon)
\end{align}
$$

As initial analysis showed that there was no significant difference in detection probability for the two observers, we simplified the observation model to have the same detection probability for the two observers, $p_1 = p_2 = p$. The model was then fitted with the following uninformative priors:

$$
\begin{align}
p &\sim \text{Uniform}(0,1) \\
\sigma_\varepsilon  &\sim \text{Uniform}(0,5)
\end{align}
$$

To inform priors when fitting the full model to the data from the sampling areas, we first logit-transformed the posterior samples of $p$ (here denoting the vector of posterior samples as $\mathbf{p}$),

$$
\boldsymbol{\eta} = \log \left( \frac{\mathbf{p}}{1-\mathbf{p}} \right)
$$

For the full model applied to data from the sampling areas, we then specified the priors for detection probability as

$$
\begin{align}
\eta_1  &\sim \text{N} \left( \text{mean}(\boldsymbol{\eta}),1.2\text{sd}(\boldsymbol{\eta}) \right) \\
\eta_2  &\sim \text{N} \left( \text{mean}(\boldsymbol{\eta}),1.2\text{sd}(\boldsymbol{\eta}) \right) \\
p_1 &= \frac{1}{1+e^{-\eta_1}} \\
p_2 &= \frac{1}{1+e^{-\eta_2}} \\
\end{align}
$$

Here, the standard deviations were conservatively increased by 20% to account for the fact that detection probabilities inside and outside of the enclosure could be different.

## Posterior predictive checks and model modifications

We performed posterior predictive checks [@gelman2004; @conn2018] with respect to both $Y_i$’s and $\mathbf{y}_i$’s by comparing the summed Pearson residuals for observed and simulated data in every step of the MCMC-chains. Bayesian p-values did not indicate any lack of fit with respect to $Y_i$’s ($p > 0.4$), but there appeared to be a lack of fit with respect to $\mathbf{y}_i$’s ($p < 0.03$), indicating that there were more variation in the counts from the two independent observers than expected if detection probability is constant across sites for each observer. To accommodate this variation in the model, we introduced random detection probabilities, assuming the logit-transformed detection probabilities to be normal. Hence, in our final observation model, we used

$$
\begin{align}
p_{1,i} &= \frac{1}{1+e^{-\eta_1 + \epsilon_{1,i}}} \\
p_{2,i} &= \frac{1}{1+e^{-\eta_2 + \epsilon_{2,i}}} \\
\epsilon_{1,i} &\sim \text{N}(0,\sigma_p)\\
\epsilon_{2,i} &\sim \text{N}(0,\sigma_p)\\
\end{align}
$$

To facilitate model fitting, we used a somewhat informative prior for $\sigma_p$,

$$
\sigma_p  \sim \text{Uniform}(0.1,0.59)
$$

The lower bound of $0.1$ was set to avoid poor mixing when the chains entered flat parts of the likelihood surface, and the upper bound of $0.59$ was selected based on a prior assessment that detection at the 97.5 percentile site should have a maximum of 10 times higher odds than in the 2.5 percentile site ($\log(10)/(1.96 \times 2) \approx 0.59$)

Bayesian p-values did not indicate any lack of fit of this final model with respect to $Y_i$’s ($p = 0.50$) or $\mathbf{y}_i$’s ($p = 0.20$).

## Implementation and model selection

The models were fitted by the use of Bayesian MCMC sampling in NIMBLE (v1.1.0; [@devalpine2024a; @valpine_programming_2017]). Convergence was assessed on three independent MCMC chains (with different start values) with the @gelman1992 diagnostics using the ‘gelman.diag-function’ in the ‘coda’ package ver. 0.19-4.1 [@plummer2006] in R ver. 4.3.3 [@rcoreteam2024].

For each of the three models for the random Poisson expectation (log-normal, exponential and gamma), we fitted both linear and quadratic models for $\mu_i$ as a function of distance from the field, as well as a model with no covariate effects; hence obtaining 9 models. We selected the best model according to the Watanabe-Akaike (Widely Applicable) Information Criterion, WAIC [@watanabe2010] for presentation of estimates and prediction (the criterion seeks to minimize the prediction error variance as an optimal trade-off between accuracy and precision of the fitted model predictions).

We initially ran MCMC-sampling on each of the nine models with 3 chains with random and independent starting values for 180,000 iterations after a burn-in of 20,000 iterations and stored every 6^th^ posterior sample. Repeating this three times showed a consistent ranking of the models by the WAIC criterion. The models with the lowest (best) WAIC values where then run for 1,080,000 samples after a burning of 20,000 iterations in 3 chains and stored every 18^th^ sample, obtaining in total 3 times 60,000 posterior samples used for inference. The upper 95% confidence limit for the [@gelman1992] ‘potential scale reduction factor’ (psrf) was \<1.025 for all parameters in the final models, and the multivariate psrf was less than 1.005.

# Detailed analysis and results {#sec-S2}

## Organization of the data

All data are in the `data` folder of the repository. The data-files included here are:

-   `SiteData.rda`: The full data from the study sites (excluding enclosure). See `SiteDataInfo.html` for description of the variables.
-   `CountData.rda`: Based on `SiteData.rda`, but includes only counts in a long format.
-   `CountData_Fence.rda`: Counts in a long format from the enclosure.
-   `nimbleData.rda`: Data from the study sites organized for NIMBLE models. File is produced by the script in `data\Make_nimbleData.R`.
-   `nimbleData_Fence.rda`: Data from the enclosure organized for NIMBLE models. File is produced by the script in `data\Make_nimbleData_Fence.R`.

## Enclosures

The enclosure contained a total of 117 red deer in a 5 hectare area of natural forest. Two surveys (flights) were conducted over the enclosures; one at 40 m above ground, and one at 60 meter above ground. We used these data to first test the method, and then to obtain information about detection probabilities, which we used to inform priors for detection probabilities in the models fitted to the wild deer data (see Supplemental Information S1).

Since the focal images from the enclosure is not a random

### Posterior predictive checks

### Deer numbers

<Bruk her full opprinnelig model>

### Detection probabilities

<Bruk som før>

## Wild deer

### Overview of data

### Convergence and WAIC of candidate models

### WAIC-best model

### Posterior predictive checks

### Predictions from best model

#### Number of deer at the sample sites

#### Densities

## References {.unnumbered}
